# Generated by Django 4.2.4 on 2023-11-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_editor_date_joined_editor_first_name_editor_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='username',
        ),
    ]
