# Generated by Django 4.2.5 on 2023-11-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "editor_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Editor",
                "verbose_name_plural": "Editors",
            },
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "reviewer_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("scopus_id", models.CharField(max_length=255)),
                ("scholar_id", models.CharField(max_length=255)),
                ("other", models.JSONField()),
            ],
            options={
                "verbose_name": "Reviewer",
                "verbose_name_plural": "Reviewers",
            },
        ),
        migrations.CreateModel(
            name="Upload_Data",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "editor_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master.editor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload_Data",
                "verbose_name_plural": "Upload_Datas",
            },
        ),
    ]
